[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-origin"
    Origin-Agent-Cluster = "?1"
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=*, camera=(), display-capture=(), encrypted-media=*, fullscreen=*, geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), xr-spatial-tracking=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/corridoros_dashboard.html"
  status = 200

[[redirects]]
  from = "/advanced"
  to = "/corridoros_detailed.html"
  status = 200

[[redirects]]
  from = "/detailed"
  to = "/corridoros_detailed.html"
  status = 200
[[redirects]]
  from = "/simulator"
  to = "/corridoros_simulator.html"
  status = 200
