[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/"
  to = "/corridoros_advanced.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/corridoros_dashboard.html"
  status = 200

[[redirects]]
  from = "/simulator"
  to = "/corridoros_simulator.html"
  status = 200
