apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: corridoros
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: corridoros
  namespaceSelector:
    any: true
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
