apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: corridors.corridoros.io
spec:
  group: corridoros.io
  scope: Namespaced
  names:
    plural: corridors
    singular: corridor
    kind: Corridor
    shortNames: [cor]
  versions:
  - name: v4
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: [type, lanes, lambdaNm, minGbps, latencyBudgetNs]
            properties:
              type: {type: string}
              lanes: {type: integer, minimum: 1}
              lambdaNm:
                type: array
                items: {type: integer}
              minGbps: {type: integer}
              latencyBudgetNs: {type: integer}
              attestationRequired: {type: boolean}
              qos:
                type: object
                properties:
                  pfc: {type: boolean}
                  priority: {type: string}
          status:
            type: object
            properties:
              id: {type: string}
              state: {type: string}
              achievableGbps: {type: integer}
              ber: {type: number}
              message: {type: string}
