[package]
name = "corridoros-sdk"
version = "4.0.0"
edition = "2021"

[lib]
name = "corridoros_sdk"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

