name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Check for FIREBASE_TOKEN
        id: has_token
        shell: bash
        run: |
          if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
            echo "token=false" >> "$GITHUB_OUTPUT"
          else
            echo "token=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Deploy Hosting
        if: steps.has_token.outputs.token == 'true'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --project redsealovers-3e10d --non-interactive

      - name: Skip Firebase (no token configured)
        if: steps.has_token.outputs.token != 'true'
        run: echo "Skipping Firebase deploy: FIREBASE_TOKEN not set as a repo secret."
